### PR TITLE
Development

### PR DESCRIPTION
**Pull request by katherinevfry**
## Description
Added ERD, wireframe, color palette, and deployed links

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by TrinityChristiana** [comment]
Checking PR Progress
- [X] Getting the application deployed (FB and Netlify are set up)
- [ ] Updating the ERD if you think you’ll need to update the Data structure
    - [Added Comment](https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/pull/125#issuecomment-815175380) 
- [x] Tickets are created
- [ ] Tickets are assigned to milestones
    - [Added Comment](https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/pull/125#issuecomment-815246652) 
- [x] Tickets are assigned to Team members
- [x] Add new links to README.md (ERD, Netlify Link)

**Comment by TrinityChristiana** [comment]
Just looked at the ERD and you all need to rethink the reservations relationship. [Look at the Requirements](https://gist.github.com/drteresavasquez/0212063d70292cd926ac7959df6df827#reservations-1). 

You will need to use an intermediary table. Especially with this requirement "As a user I should be able to assign staff members to reservations." Notice Staff members are plural.

**Comment by TrinityChristiana** [comment]
We want to separate out the tickets in more than one milestone as well.

**Comment by TrinityChristiana** [comment]
## Clarifications
I realized we never determined the sold-out feature. In the instructions it says:
> As a user I should not be able to assign a menu item to a reservation if any of the ingredients from that menu item are sold out.

To clarify sold out, every time a menu item is added to a reservation, each ingredient that's on the menu item's quantity should decrease by 1.

## Few questions for the ERD

1. How do you plan on determining the `final_bill` of the reservation?
1. Menu items should be able to be added to different reservations right? The ERD currently says that a menu item can only belong to one reservation.
1. What is `staff_required`? What's an example of how that would look? 
1. Seating should be able to be added to different reservations right? The ERD currently says that one seating can only belong to one reservation.
1. How will you determine how many of an ingredient is currently in stock.

**Review by TrinityChristiana — APPROVED** [review]
Everything looks great! You're approved to start working on your first milestone.

**Review by chiestroud — APPROVED** [review]
Awesome！

**Pull request merged**
